---
# Service
apiVersion: v1
kind: Service
metadata:
  name: httpd-service-nautilus
  namespace: httpd-namespace-nautilus
spec:
  type: NodePort
  selector:
    app: httpd-nautilus
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
    protocol: TCP
